### ISSUE TITLE
Error when adding delegate...

### ISSUE THREAD

**Issue by evision1** [richzertuche/ZCarousel#3]
I am getting an error  "Type AudioViewController"  does not conform to protocol  "ZCarouselDelegate"

![screen shot 2015-09-26 at 2 18 13 pm](https://cloud.githubusercontent.com/assets/9320855/10119903/7f2478f8-6459-11e5-93db-448c42c1fc90.png)

**Comment by evision1** [comment]
nevermind, I jumped the gun. It showed an error message until i added the "ZCarouselShowingIndex" function.

**Comment by richzertuche** [comment]
No problem!
Hope you find it useful!
